### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by Felleus** [DrkMatr1984/ChatBubbles#1]
Please, update plugin for the 1.18 version

**Comment by DrkMatr1984** [comment]
It seems to work on 1.18 for me, but I will try to recompile with 1.18 as depends and see what happens.

**Comment by DrkMatr1984** [comment]
It was fine, but I made some small updates to ensure compatibility. :)

https://github.com/DrkMatr1984/ChatBubbles/releases/tag/1.18
